let users = [
    {
        id: 1,
        name: "Isa Aliyev",
        age: 28,
        salary: 2500,
        birthYear: 1997,
        role: "Frontend Developer",
        department: "IT",
        experience: 4,
        experienceType: "year",
        city: "Baku",
        isActive: true,
        photo: "https://i.pravatar.cc/150?img=1"
    },
    {
        id: 2,
        name: "Said Memmedov",
        age: 32,
        salary: 3200,
        birthYear: 1993,
        role: "Backend Developer",
        department: "IT",
        experience: 6,
        experienceType: "year",
        city: "Sumqayit",
        isActive: true,
        photo: "https://i.pravatar.cc/150?img=2"
    },
    {
        id: 3,
        name: "Elsha Hesenovd",
        age: 24,
        salary: 1800,
        birthYear: 2001,
        role: "UI Designer",
        department: "Design",
        experience: 8,
        experienceType: "month",
        city: "Baku",
        isActive: false,
        photo: "https://i.pravatar.cc/150?img=3"
    },
    {
        id: 4,
        name: "Pervi Quliyevz",
        age: 30,
        salary: 3200,
        birthYear: 2001,
        role: "Backend Developer",
        department: "IT",
        experience: 7,
        experienceType: "year",
        city: "Ganja",
        isActive: true,
        photo: "https://i.pravatar.cc/150?img=4"
    },
    {
        id: 5,
        name: "Aysel Kerimova",
        age: 27,
        salary: 2100,
        birthYear: 1998,
        role: "Frontend Developer",
        department: "IT",
        experience: 3,
        experienceType: "year",
        city: "Baku",
        isActive: true,
        photo: "https://i.pravatar.cc/150?img=5"
    },
    {
        id: 6,
        name: "Nurla Ibrahimovn",
        age: 35,
        salary: 4000,
        birthYear: 1999,
        role: "Project Manager",
        department: "Management",
        experience: 10,
        experienceType: "year",
        city: "Baku",
        isActive: true,
        photo: "https://i.pravatar.cc/150?img=6"
    },
    {
        id: 7,
        name: "Gunel Abdullayeva",
        age: 26,
        salary: 1900,
        birthYear: 1999,
        role: "UI Designer",
        department: "Design",
        experience: 14,
        experienceType: "month",
        city: "Sumqayit",
        isActive: false,
        photo: "https://i.pravatar.cc/150?img=7"
    },
    {
        id: 8,
        name: "Tural Ismayilov",
        age: 29,
        salary: 2700,
        birthYear: 1996,
        role: "DevOps Engineer",
        department: "IT",
        experience: 5,
        experienceType: "year",
        city: "Baku",
        isActive: true,
        photo: "https://i.pravatar.cc/150?img=8"
    },
    {
        id: 9,
        name: "Leyla Huseynova",
        age: 31,
        salary: 3300,
        birthYear: 2004 ,
        role: "Project Manager",
        department: "Management",
        experience: 9,
        experienceType: "year",
        city: "Ganja",
        isActive: true,
        photo: "https://i.pravatar.cc/150?img=9"
    },
    {
        id: 10,
        name: "Rasha Qasimovd",
        age: 23,
        salary: 1700,
        birthYear: 2004,
        role: "DevOps Engineer",
        department: "IT",
        experience: 6,
        experienceType: "month",
        city: "Baku",
        isActive: false,
        photo: "https://i.pravatar.cc/150?img=10"
    }
];